CREATE DATABASE CRUD
GO
USE CRUD
GO
CREATE TABLE CLIENTE(
ID INT IDENTITY PRIMARY KEY,
TIPO CHAR(1) NOT NULL,
NOME VARCHAR(100) NOT NULL,
CPFCNPJ VARCHAR(14) NOT NULL,
RGIE VARCHAR(12) NULL,
DTHORA DATETIME NOT NULL DEFAULT(GETDATE()),
ATIVO BIT NOT NULL DEFAULT(1))
GO
CREATE TABLE TELEFONE(
CLIENTE INT NOT NULL,
DDD TINYINT NOT NULL, 
TELEFONE VARCHAR(9) NOT NULL)
GO
ALTER TABLE TELEFONE
ADD CONSTRAINT ID_CLIENTE_TELEFONE_FK FOREIGN KEY (CLIENTE) REFERENCES CLIENTE(ID)
GO
CREATE TABLE ENDERECO(
CLIENTE INT NOT NULL,
LOGRADOURO VARCHAR(150) NOT NULL,
NUMERO SMALLINT NOT NULL,
CEP CHAR(8) NOT NULL,
BAIRRO VARCHAR(100) NOT NULL,
CIDADE VARCHAR(100) NOT NULL,
UF CHAR(2) NOT NULL,
PAIS VARCHAR(100) NOT NULL)
GO
ALTER TABLE ENDERECO
ADD CONSTRAINT ID_CLIENTE_ENDERECO_FK FOREIGN KEY (CLIENTE) REFERENCES CLIENTE(ID)